//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class content_access_existing
    {
        public int id_user { get; set; }
        public string EMPLOYEEID { get; set; }
        public string USERID { get; set; }
        public string RMUSER { get; set; }
        public string UNAME { get; set; }
        public int id_organization { get; set; }
        public string ORGANIZATION_NAME { get; set; }
        public Nullable<int> id_content { get; set; }
        public string CONTENT_QUESTION { get; set; }
        public Nullable<System.DateTime> LASTACCESS { get; set; }
        public string LOCATION { get; set; }
        public string zone_title { get; set; }
        public string user_designation { get; set; }
        public string USTATUS { get; set; }
    }
}
