//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class dummy_map
    {
        public int id_category_association { get; set; }
        public Nullable<int> id_parent { get; set; }
        public Nullable<int> id_category { get; set; }
    }
}
