//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_profile
    {
        public int ID_PROFILE { get; set; }
        public int ID_USER { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public Nullable<int> AGE { get; set; }
        public string LOCATION { get; set; }
        public string EMAIL { get; set; }
        public string MOBILE { get; set; }
        public string GENDER { get; set; }
        public string DESIGNATION { get; set; }
        public string CITY { get; set; }
        public string OFFICE_ADDRESS { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public Nullable<System.DateTime> DATE_OF_JOINING { get; set; }
        public string REPORTING_MANAGER { get; set; }
    }
}
