//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_overall_assessment_user_log
    {
        public int srno { get; set; }
        public Nullable<int> userid { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public Nullable<double> percentage { get; set; }
    }
}
